kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      name: ${SERVICE_NAME}
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${SERVICE_NAME}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        - name: ${SERVICE_NAME}-grpcgateway
          image: ${SERVICE_NAME}-grpcgateway
          ports:
            - containerPort: 18080
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: "0.5"
            requests:
              memory: 64Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: "/${SERVICE_NAME}/v1/health"
              port: 18080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/${SERVICE_NAME}/v1/health"
              port: 18080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 2
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr
