commonLabels:
  app: ${SERVICE_NAME}

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ${SERVICE_NAME}
    newName: ghcr.io/${ORG_NAME}/${SERVICE_NAME}
    newTag: $IMAGE_TAG
  - name: ${SERVICE_NAME}-grpcgateway
    newName: ghcr.io/${ORG_NAME}/${SERVICE_NAME}-grpcgateway
    newTag: $IMAGE_TAG
